### ISSUE TITLE
Resume swap after restart of cnd

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1061]
Assumptions:
- Btsieve is still running
- Btsieve still holds the previous queries with the same ids

Notes regarding the current state machine:
Currently, the state machine is based on futures and advanced "by itself" as these futures resolve. This is suboptimal for a number of reasons:
- It is hard to restart from an intermediate state/mid-swap (this ticket)
- It forces the module providing the state machine to depend on many dependencies (making it hard/impossible) to provide it in the form of a library
- It is very big in terms LoC (an approach not based on futures is probably much smaller)

Notes regarding the ticket:
With a different implementation of the swap protocol state machine, this ticket might be much easier because no "advancing" whatsoever is needed.

**Comment by thomaseizinger** [comment]
> Grab the handle for the "accept future" and re-inject the accept data.

Recovering from "mid-communication" will probably never work. Here is why:

Currently, restarting `cnd` during an on-going communication (waiting for SWAP RESPONSE or waiting for user to accept/decline) will kill the communication even if we would have persistent storage.

This is due to two things:

1. We are using channels to
a) represent a pending request that will eventually be answered by a response:
https://github.com/comit-network/comit-rs/blob/90348b62d987ee702ece4285eaf79c5db0609991/comit_node/src/libp2p_bam/behaviour.rs#L77
b) represent a pending incoming request that will either be accepted or declined:
https://github.com/comit-network/comit-rs/blob/90348b62d987ee702ece4285eaf79c5db0609991/comit_node/src/libp2p_bam/handler.rs#L268
A channel cannot be persisted between restarts because it basically is just a pointer to another memory location.

2. Our messaging protocol & implementation is not stateless: We are relying on the substream being available during the whole communication process. As a consequence, it is only feasible to retry the whole communication if a substream breaks down instead of trying to recover from the intermediate state of the substream before it broke down.

**Comment by tcharding** [comment]
I'd like to work on this one.  If someone picks this up can I pair with you please?

**Comment by tcharding** [comment]
> Recovering from "mid-communication" will probably never work.

The stated aim is to restart swaps 'in progress', we can simply define swaps as in progress only *after* both request/response messages.
