### ISSUE TITLE
How to define/deal with custom errors?

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1194]
## Problem

Error handling in Rust is non-trivial and can lead to a lot of boiler plate code.

1. We currently define a new error type per module for functions within the module to share them.

2. If function needs to return an error by bubbling up from 2 different Error enums then such function needs to have its own Error enum to wrap those and need conversions From those.

## Goal

To reach project consensus on a nice way to do error handling and start to move towards doing so in a consistent manner in our codebase.

## Ideas

List of libraries (to be extended):

- https://crates.io/crates/custom_error
- https://crates.io/crates/error-chain
- https://crates.io/crates/failure
- https://crates.io/crates/snafu
- https://jeltef.github.io/derive_more/derive_more/from.html#enums
- https://github.com/dtolnay/thiserror

Conclusion: those interested can do it as a side task and use a new way in a PR (ie, PoC). If it's good, we could make it the CoBloX standard for handling errors.

**Comment by thomaseizinger** [comment]
I am not really a fan of this kind of macro-based programming. Either hide all of the generated code from my completely (like custom derives) or don't generate code I am supposed to use :D

Autocompletion is usually also bad for these things (although CLion got drastically better at this already).

There have many several attempts at making this better in the Rust ecosystem:
- error_chain
- failure
- custom_error

Personally, I would like to see a PoC that clearly shows the added benefit of using such a library without compromising the flexibility that we have now.

Regarding the number of errors types: Did you grep across the whole repository? Then the number is quite misleading because it completely ignores the fact that we have certain module boundaries that exist on purpose and hence need to define their own error type.

**Comment by thomaseizinger** [comment]
Nevertheless, we can/should do something about the situation.
I'd propose creating a spike that investigates the state of the art error handling.
We can collect some libraries here that may help:
- https://github.com/shepmaster/snafu

**Comment by thomaseizinger** [comment]
There is a crate called `derive_more` that allows you to derive the `From` trait which could be useful to not having to write that impl manually for our custom error types:

https://jeltef.github.io/derive_more/derive_more/from.html#enums

**Comment by thomaseizinger** [comment]
@bonomat why did this get closed? I don't see this issue being resolved and it actually came up recently here: https://github.com/comit-network/comit-rs/issues/1582

**Comment by tcharding** [comment]
The `anyhow` crate is likely the answer to this issue.  We have started using it already (see `cnd/src/db/mod.rs`).

ref: https://docs.rs/anyhow/1.0.19/anyhow/
