### ISSUE TITLE
Add persistent storage to cnd

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#1243]
cnd persistent storage epic - A.K.A. Sqlite database. 

https://app.zenhub.com/workspaces/coblox-scrum-5be4c2ea4b5806bc2bf2d351/issues/comit-network/comit-rs/1243

## Problem

Currently cnd only stores swaps in memory.  This means we can only expose to cnd clients the swaps done since the current cnd process was started.  ~Also we cannot continue in-progress swaps if the node restarts.~ (this is described by issue #1244).

## Goal

Store all swaps persistently (i.e., on disk) so that cnd exposes all swap history and restart in-progress swaps.

Spike 9 (https://github.com/comit-network/spikes/blob/master/0009-comit-btsieve-db.adoc) describes adding a database to cnd in order to save these states to disk. There seems to be no disagreement from the team on the recommendations within this spike.

**Comment by tcharding** [comment]
Adding a plan of attack here for comments or suggestions.  Intend to first put together a draft PR with scope limited to swap metadata.  This will mean clients can list all previous swaps but not get any information on them.  If I understand correctly, this means only implementing an Sqlite backed version of `MetadataStore`.  For API queries on a swap id that was created by a previous instance of cnd the query will return `problem::state_store`.

**Comment by thomaseizinger** [comment]
> Adding a plan of attack here for comments or suggestions. Intend to first put together a draft PR with scope limited to swap metadata. This will mean clients can list all previous swaps but not get any information on them. If I understand correctly, this means only implementing an Sqlite backed version of `MetadataStore`. For API queries on a swap id that was created by a previous instance of cnd the query will return `problem::state_store`.

Yes that seems reasonable.
I had another thought though and just realized that we may have been to quick in dismissing two of the tasks you added to the list above, sorry for that :(

At the moment, the e2e tests restart cnd and btsieve for each test to ensure an empty state. As soon as we have a database, that is no longer true. I think the e2e tests will actually break because the often assume that the list of swaps is empty in the beginning. Hence, you will need to modify the test harness to delete the database between the tests.
That in turn raises the question about the location of the database if several instances are running (do we want to have a `data_dir` commandline argument to override that?).

I think it would make sense to start with a PR that adds the following functionality:
- create a database on startup if it does not exist yet
- allows users to somehow override where it is stored (`directories-rs` has a `data_dir` so I'd suggest we add a commandline option to override that which we can use in the e2e tests)
- create an initial "hello-world" migration that is executed as the cnd starts up

All of that can be done in a PR that can be merged right away. That way we have the necessary infrastructure in place that we need for the other usecases.

**Comment by tcharding** [comment]
# Direction to take in tackling the persistent storage issue

We are trying to add an Sqlite database to achieve two things

- Past swaps are stored and shown to the client after cnd restarts
- In progress swaps can be continued if we crash mid swap

## Ideal functionality

When sending a swap request

1. store it in the database
2. instruct network layer to send message to other party

When receiving SWAP REQUEST

3. store it in the database

When receiving SWAP RESPONSE

4. check if swap with specified ID exists
5. store received data in database
6. spawn state machine

When listing all swaps

7. load all swaps from the database
8. construct actions based on their state

When triggering accept

9. load particular swap from database
10. check if it is in the correct state
11. store new information in database
12. instruct network layer to send message to other party
13. spawn state machine


(1) + (2): We already do that (and more because we also spawn the state machine. the communication step would have to be removed from the state machine here)
(3): We currently spawn the state machine right away, I recommend to not do that and instead just store the received data in the database
(4) + (5) + (6): This does not exist yet because the communication step is part of the state machine and linked to the request through a channel
(7): We would only store the request + response data and not transaction we witnessed, so this would only return this data
(8): Minor change here, accept and decline currently depend on memory-only channel state. those actions would need to be created simply be looking at what data we already exchanged and what is missing
(9) + (10): can already do that
(11): would need to happen as part of the execution of the /accept controller, currently happens in the state machine
(12): we cannot do that at the moment because the interface to our network layer is channel-based. the interface we want is probably: fn(peerid, message) -> void, where message contains the swapid so that the other party can identify that. this is likely the biggest change: we would need to change the way we handle substreams to: open -> send -> close instead of open -> send -> receive -> close

## Just save/show completed swaps

In order to just save completed swaps we can do a (slightly modified) subset of the tasks above.
Only write the swap to the database when the swap completes, then do (7), do we need (8)?

**Comment by thomaseizinger** [comment]
@tcharding This was not meant to be posted here :sweat_smile:

Mainly because a)
- it is not complete
- the notes were not written for anyone else to actually follow along - I would have written them differently if we want to use them as a base for discussion.
