### ISSUE TITLE
Can't run cnd/btsieve release binaries on Ubuntu 19.04

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-rs#1366]
When running cnd's binary from the [first release](https://github.com/comit-network/comit-rs/releases/tag/0.1.0)
```
./cnd
```
I get the following error:
```
./cnd: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

The same thing happens for btsieve.

**Comment by D4nte** [comment]
This is because we compile on ubuntu:16.04 and Lucas uses ubuntu:19.04.

Ubuntu 16.04 most recent libssl available is 1.0.2 whereas it's 1.1.1 on Ubuntu 19.04.

Because the binary is created with dynamically links, then it expected to have 1.0.2 available on the machine (but only 1.1 is available).

I see 3 solutions:
1. We do static linking for libssl & libcrypto, the binary generated would be a bit bigger but it would avoid these kind of issues.
2. We provide a binary for both Ubuntu 16.04 and 19.04
3. We do 1 & 2 (3 Linux binaries)

I recommend 1.
