### ISSUE TITLE
Flaky e2e test

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1719]
The new e2e test is flaky: https://app.circleci.com/jobs/github/comit-network/comit-rs/2885

**Comment by luckysori** [comment]
I attempted to tackle it's flakiness with https://github.com/comit-network/comit-rs/pull/1689/commits/5f0b5a3bd9cb6775760974a98bdffdef6ab67996 by reintroducing the use of `chai-as-promised`. I don't think this will fix it completely, as it was already flaky when `chai-as-promised` was being used, but it should at least prevent errors caused by checking the balance too early.

**Comment by bonomat** [comment]
Imho part of the flakiness came from the new format: we did not kill the cnd nodes. Hence, we had multiple nodes running which slowed down bitcoind bigtimes. This led to timeouts in our e2e tests. 
I tried to fix this in this PR: #1769

**Comment by luckysori** [comment]
> 
> 
> I attempted to tackle its flakiness with [5f0b5a3](https://github.com/comit-network/comit-rs/commit/5f0b5a3bd9cb6775760974a98bdffdef6ab67996) by reintroducing the use of `chai-as-promised`. I don't think this will fix it completely, as it was already flaky when `chai-as-promised` was being used, but it should at least prevent errors caused by checking the balance too early.

Also, @thomaseizinger realised that `chai-as-promised` does not do what I thought it did, so we stopped using it.
