### ISSUE TITLE
Re-model our ledgers to represent the networks (Ethereum)

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#1947]
_Split of #1867_

## Problem

Our current ledgers are `Bitcoin` and `Ethereum`.
Those structs have a `network` field inside which represents, which network we are actually talking about.
This makes it unergonomic to express code that is specific to a particular network or handle requirements like disallowing swaps between different networks. 

More information is captured on the [relevant spike](https://github.com/comit-network/spikes/blob/master/0019-domain-model.adoc).

## Goal

Re-model our ledgers to what is recommended in the spike.

## Recommendation

Split the current `Ledger` struct into (at least) 3, one per `chain-id` that we support.

For dev chain (we use 17), we should have a struct that is `Custom` network and support any chain id (apart from 3 and 1). This should be considered a "regtest" network (e.g, do not implement mainnet-custom traits).

Note: `impl_template` crate is likely to be of use here.

Note: Feel free to add macros but don't over do it.
⚠️Disclaimer: this is going to be an exploratory hence the estimation of 21.

**Comment by tcharding** [comment]
This issues is blocked.  I do not know how to progress further on it.  Blocked for the following reasons
- The Bitcoin side does _not_ do what the spike recommends, specifically there is no mod `crate::ledgers` module.  There are 3 lots of code, one for each Bitcoin Network.
- Ethereum cannot be implemented the same as Bitcoin currently is because of this function
```
 impl<B: ledger::Bitcoin> Ledger for B {
    type HtlcLocation = OutPoint;
    type Identity = PublicKey;
    type Transaction = Transaction;
}
```
This does not do what it looks like it does because the compiler ignores the trait bound.

So without modifying the Bitcoin side I do not know how to move forward, and I do not know how to modify the Bitcoin side because I do not fully understand where this work is supposed to be going i.e., I don't fully understand the motivation and benefits we are trying to realise.

**Comment by thomaseizinger** [comment]
Thanks for raising this, I will investigate this!

**Comment by bonomat** [comment]
@thomaseizinger : this has been in the to-refine pipeline for a while now. Is this still being refined or can we move it back into to-groom?

**Comment by thomaseizinger** [comment]
> @thomaseizinger : this has been in the to-refine pipeline for a while now. Is this still being refined or can we move it back into to-groom?

Nope, the last edit as per GitHub was 20 days ago. I wasn't able to work on it yet :)

**Comment by thomaseizinger** [comment]
It turned out that for other reasons, we are going to [remove the `Ledger` trait](https://github.com/comit-network/comit-rs/issues/2081) altogether which solves the problem that is blocking this issue.

I've set the dependency so this can be considered refined and is ready to be re-groomed.

**Comment by D4nte** [comment]
@thomaseizinger should we move that to grooming?

**Comment by thomaseizinger** [comment]
Yes, that sounds like a good idea!

**Comment by thomaseizinger** [comment]
This seems to be the reference for a name <-> chain ID mapping: https://chainid.network/

**Comment by thomaseizinger** [comment]
Closing this because it turns out this model doesn't work as nicely as originally intended.

Also see here: https://github.com/comit-network/comit-rs/pull/2623#discussion_r424094938
