### ISSUE TITLE
Extend our e2e test suite with Lightning nodes

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#1951]
## Problem

In order to verify that our Lightning integration works, we need to test it. This in turn requires us to extend our e2e test suite with at least two Lightning nodes.

## Goal

Test the Lightning integration.
Have one test that:
- requires lnd
- Bob adds an invoice
- Alice sends a payment to Bob
- Check balances

## Recommendation

Lightning channels, compared to the whole blockchain, are per user. Even though several tests could share the same lnd instance, I feel it would be better if each tests starts their own lnd instance. Contrary to blockchain nodes, we definitely need one lnd instance per actor. We do start one cnd instance per actor, hence starting one lnd instance per actor seems natural as-well.

In the case of a LN swap, we need to:

- send money to lnd's wallet
- open a channel (should both parties have money in the beginning to make this part independent of the swap combination?)

Note: lnd needs to be compiled with the correct feature flag: `make tags=invoicesrpc`. As part of this issue you need to provide such binary (docker?)

Note: upon starting, lnd scans the blockchain to find any htlc or transactions related to its wallet/channels. This may take some time and make explain a delay in seeing money sent to its wallet.

**Comment by thomaseizinger** [comment]
This is blocked by https://github.com/comit-network/comit-rs/issues/1927 to make sure our e2e test suite is ready handle more combinations of swaps without the total test time scaling linearly.

**Comment by bonomat** [comment]
I remove the block of https://github.com/comit-network/comit-rs/issues/1927. 

It's more a _soft block_ in the way that we should not have two people working on both tickets at the same time. It is not a functional block, i.e. nothing in this setup is blocked by the other one. 

If we want to prevent 2 people working on these issues in parallel, we could turn the block around?

**Comment by thomaseizinger** [comment]
> If we want to prevent 2 people working on these issues in parallel, we could turn the block around?

I don't want https://github.com/comit-network/comit-rs/issues/1927 to fall under the table :)

I am fine with not having a dependency as long as it still gets done.
Certainly, I would not put the dependency in the other direction.

**Comment by tcharding** [comment]
Putting this back to the start of the pipeline after working on it for a sprint.  Draft PR: https://github.com/comit-network/comit-rs/pull/1984 adds the LND nodes, a sanity test, and skeleton `Actor` methods to glue it all together.

After much pain trying to use REST API I switched to trying to use the gRPC API.  Reasoning was, since I couldn't get the REST API to play nicely and we need to have gRPC stuff for the js-sdk later (and most likely for the e2e tests also) then why not just do it now.

Dropping this because its the end of the sprint and I've banged my head against it long enough.  Happy to pair if someone picks this up and/or share anything else I learned.
