### ISSUE TITLE
Extend assertion of Bitcoin high fee e2e test

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-rs#2046]
## Problem

Some of the assertions got lost because the comit-js-sdk does not support the `application/problem+json` media type properly.

## Goal

Assert that the response has status `400` (like in the old e2e test, see: 

## Proposed Solution

Once the SDK ticket was done add this assertion:

```
await expect(responsePromise).to.be.rejected
    .and.be.instanceOf("Problem")
    .and.have.property("status", 400);
```

**Comment by bonomat** [comment]
I don't think this is technical debt though.

**Comment by bonomat** [comment]
I'm not convinced we should write an e2e test here: 

* `256: absurdly-high-fee` is a feature of bitcoind. It prevents broadcasting transactions where `fee > maxtxfee`.  One can configure bitcoind with `-maxtxfee=` to change the max allowed fee. 
* I think with this test we would assert that `-maxtxfee=` works as expected and that we can catch the error
* since transactions are broadcasted through the sdk, we should test this behavior in the sdk

@da-kami : what do you think?

**Comment by da-kami** [comment]
Fine with me - I agree it was weird having it in the e2e test.


> I'm not convinced we should write an e2e test here:
> 
> * `256: absurdly-high-fee` is a feature of bitcoind. It prevents broadcasting transactions where `fee > maxtxfee`.  One can configure bitcoind with `-maxtxfee=` to change the max allowed fee.
> * I think with this test we would assert that `-maxtxfee=` works as expected and that we can catch the error
> * since transactions are broadcasted through the sdk, we should test this behavior in the sdk
> 
> @da-kami : what do you think?

Fine with me - I agree it was weird having it in the e2e test.
Is there a follow up ticket on the SDK necessary? 
(not closing this one until above question was answered; feel free to close it yourself :)

**Comment by bonomat** [comment]
Given the uncertainty of where to add the test I don't see this as a high priority. Closing this now and wait until it comes up again.
