### ISSUE TITLE
Investigate alternative strategies for implementing the communication layer using the new oneshot protocols

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2388]
## Problem

[Spike 23](https://github.com/comit-network/spikes/blob/master/0023-communication-protocol.adoc) defines a new set of libp2p protocols that can be orchestrated to achieve the communication necessary for starting  a swap.

An initial version of this was implemented by the LN Mob. This initial version is based on having a `NetworkBehaviour` per protocol and later composing those together with the derive of `NetworkBehaviour`.

This has several problems:

- Even if we don't see it, the code generated by the derived NetworkBehaviour is really complicated.
- We have to either maintain a [workaround](https://github.com/comit-network/comit-rs/blob/b9ca8f3659448f2499c314da8eb6b551c0a74ef7/cnd/src/network/oneshot_behaviour.rs#L35-L42) for not keep track of our connections or re-implement [the connection handling](https://github.com/comit-network/comit-rs/blob/b9ca8f3659448f2499c314da8eb6b551c0a74ef7/cnd/src/network/protocols/announce/behaviour.rs#L57-L103) in every behaviour.
- We have several layers of libp2p components that are pretty stupid and just forward things.
- The state management is pretty ugly and doesn't scale.
We have several hashmaps in this component where we store stuff keyed by the SwapId. We also maintain several boolean flags to keep track of what already happened.

## Goal

Investigate alternative ways of implementing the required functionality that are more elegant and hence, hopefully easier to maintain.
Scaling, adding other pairs for han/herc20/halight, should be kept in mind.

## Recommendation

It sounds promising to create a `ProtocolsHandler` that can handle more than a single protocol at once, similar to the `multi` handler: https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/protocols_handler/multi.rs

Unfortunately, the multi handler requires those protocols to have the same type, which is not the case for us. It seems unlikely that we can do this generically but we don't need to. A solution tailored to our codebase is fine.

A more modular design, if possible, is likely to be the ideal solution.

**Comment by D4nte** [comment]
After some discussion with @thomaseizinger we came to the following observations:

The biggest challenge in adding a new pair (e.g. Bitcoin on-chain <> Ether) is that the only difference is one field (bitcoin address vs lightning identity), everything is the same and we want to avoid ending up copy-pasting the rest of the code.

The composition of oneshot protocol might be over-flexible for the need but at the end, it is not the real source of complexity of ComitLn.

The real complexity come from the `create_params` struct that we feed it to `ComitLn`, making it ComitLn protocol pair specific and aware. However, `ComitLn` and its child data structure `Swaps` do not need to know about the pair. They just need to know what information to send, and what information is necessary to be able to `finalize` the swap.

Which means that similarly to the composition of one shots, `ComitLn` should provide an API that allow the caller to pass the information to send and to receive. This could simply be done using a sequence of options:

```
impl ComitLn {
    pub fn initiate_communication(
        &mut self,
        id: LocalSwapId,
        create_swap_params: Herc20HalightBitcoinCreateSwapParams,
    ) -> anyhow::Result<()> {
		// ...
	}
}
```

would become
```
impl ComitLn {
    pub fn initiate_communication(
        &mut self,
        local_swap_id: LocalSwapId,
		digest: SwapDigest,
		shared_swap_id: Option<SharedSwapId>
		secret_hash: Option<SecretHash>,
        ethereum_identity: Option<identity::Ethereum>,
		lightning_identity: Option<identity::Lightning>,
		bitcoin_identity: Option<identity::Bitcoin>,
    ) -> anyhow::Result<()> {
		// ...
	}
}
```

Note how:
- The role is not communicate to ComitLn, if `shared_swap_id` is `None` then it can be deduce that an `announcement` must be sent, otherwise, that the `shared_swap_id` should be returned in a `confirmation`.
- By passing fields as `Some` it means that they will need to be sent over the wire, for the identities, it also mean that if we have an `ethereum_identity` to send, we must receive an `ethereum_identity` before finalising.

The next step will be to play with this concept and see if we can make `ComitLn` generic without using type parameters.

Finally, it should also be noted that in the case of grin<->bitcoin, the direction would be to still re-use `ComitLn` but add a new request-response (in opposition to one shot) protocol to the behaviour that would be used if a `grin_identity` is passed to the interface above.

**Comment by thomaseizinger** [comment]
> Finally, it should also be noted that in the case of grin<->bitcoin, the direction would be to still re-use `ComitLn` but add a new request-response (in opposition to one shot) protocol to the behaviour that would be used if a `grin_identity` is passed to the interface above.

For clarity, the problem with GRIN will not be that we have to send a GRIN identity but many more messages including (encryptyed/adaptor) signatures etc.

I don't think it makes sense to decompose such protocol into individual oneshots but that is something we can evaluate once we add it :)

**Comment by D4nte** [comment]
Done with #2650 and #2689

**Comment by thomaseizinger** [comment]
@D4nte how should we deal with the remaining problems that are listed in the spike and were not addressed by the linked PRs?

- Even if we don't see it, the code generated by the derived NetworkBehaviour is really complicated.
- We have to either maintain a workaround for not keep track of our connections or re-implement the connection handling in every behaviour.
- We have several layers of libp2p components that are pretty stupid and just forward things.
- The state management is pretty ugly and doesn't scale.

**Comment by D4nte** [comment]
@thomaseizinger Well spotted. I simply don't know. Your hunch was that if we streamline the storage of the data exchanged then a solution might show up for these problems. I guess it did not.

**Comment by thomaseizinger** [comment]
Let's open separate tickets for that.
