### ISSUE TITLE
Bitcoin::network does not support `test`/`main`-net 

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2438]
# Problem

We use `(rust_bitcoin)::constants::Network` for parsing the response we get from bitcoind.
However, the enum variants of `Network` do not support `test`. 

Implementation:
https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/network/constants.rs#L50-L56

RPC/Rest Documentation:
https://bitcoincore.org/en/doc/0.17.0/rpc/blockchain/getblockchaininfo/
```
...
"chain": "xxxx",              (string) current network name as defined in BIP70 (main, test, regtest)
...
```

This is a problem because we check `/rest/chaininfo.json` to get the latest blockheight. 
Deserializing the response fails for testnet (and mainnet) as the `Network` variant for testnet is `"testnet"` and for mainnet `main`.

# Goal
Correctly decode bitcoind's response (e.g. networks `main`, `test` and `regtest`). 

* https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki

**Comment by D4nte** [comment]
Isn't the goal to support decoding of `bitcoind` json rpc response?

While BIP70 might be the reason of the terminology used in bitcoind, it seems convoluted to say that we want to support BIP70 because BIP70 is what bitcoind json rpc api uses and we want to support this bitcoind jspon rpc api hence we want to support BIP70.

I propose to change the goal to: _correctly decode the mainnet value on `getblockchaininfo` bitcoind X.Y.Z rpc command response_.

**Comment by D4nte** [comment]
Isn't the goal to correctly decode bitcoind's response?

**Comment by thomaseizinger** [comment]
From BIP70:

> This BIP describes a protocol for communication between a merchant and their customer, enabling both a better customer experience and better security against man-in-the-middle attacks on the payment process.

I don't mind supporting different serializations but is BIP70 really the authoritative source for this?

**Comment by bonomat** [comment]
Please ignore BIP70, this was really not the purpose of this ticket 😅. I think solving the problem is the important thing here.
