### ISSUE TITLE
Optimize makefile

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#2474]
# Problem

The "problem" with our makefile is that we are using global variables.
Global variables in make are evaluated during makefile's "parsing" stage, not during execution stage.
And hence, the toolchain is always installed for any make target.

# Goal

Only install cargo/toolchain for make targets where it is actually needed

<details>
<summary>Notes: </summary>

To compare, check the `Run e2e test` action

No toolchain installation after changes in this branch: 
https://github.com/comit-network/comit-rs/pull/2469/checks?check_run_id=593882267

```
Run export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$HOME/go/bin:$PATH
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.55s.
yarn run v1.22.4
$ tsc && jest --forceExit
```

Toolchain being installed before changes in another branch: 
https://github.com/comit-network/comit-rs/pull/2459/checks?check_run_id=590941543

```
Run export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$HOME/go/bin:$PATH
error: toolchain '1.42.0-x86_64-unknown-linux-gnu' is not installed
error: toolchain 'nightly-2020-01-15-x86_64-unknown-linux-gnu' is not installed
info: syncing channel updates for '1.42.0-x86_64-unknown-linux-gnu'
info: latest update on 2020-03-12, rust version 1.42.0 (b8cedc004 2020-03-09)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
(cd ./api_tests; yarn install; yarn ci)
```

</details>

**Comment by thomaseizinger** [comment]
One note here: The evaluation is not the problem. I think you actually want those variables to be evaluated globally because they capture the state of the system. What we need to change is what the individual targets do, i.e. only install Rust if it is not installed & we are not on CI.

**Comment by bonomat** [comment]
Well, not really:

The problem are really these two variables which result in installing the toolchain for every target: 

https://github.com/comit-network/comit-rs/blob/baf2d529b9ff31deeddbdc0b88ec73b299c289b2/Makefile#L5

https://github.com/comit-network/comit-rs/blob/baf2d529b9ff31deeddbdc0b88ec73b299c289b2/Makefile#L8

We don't want them to be global variables.

**Comment by D4nte** [comment]
Please note a [PR](https://github.com/comit-network/comit-rs/pull/2475) is already opened to fix that so maybe best to continue the discussion there?

**Comment by thomaseizinger** [comment]
> Please note a [PR](https://github.com/comit-network/comit-rs/pull/2475) is already opened to fix that so maybe best to continue the discussion there?

I would argue for a different approach altogether :)

Our Makefile is a very thin wrapper around the standard tools of the languages we are using:

- cargo (clippy/fmt/build)
- rustup
- yarn

This is very good and the result of a constant effort to push any kind of build/test complexity down into either configuration files or code (testcontainers for example).

The only thing our Makefile is really doing is stuff that we want locally:

- installing toolchains
- installing tools like rustfmt / clippy etc
- build the binary before running tests

CI is a different environment so instead of making the Makefile more complicated, I would propose to just configure CI the way we want. As long as we keep up the effort of configuring things in the right place this is unlikely to get out of sync :)
