### ISSUE TITLE
Split protocol naming is too generic

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2533]
## Problem

When we designed the new spilt protocols we came up with some nice names (Han, HErc20, HALight).  Once again, we made a mistake in allowing a generic abstraction to creep in.  HErc20 fully describes the protocol i.e., it is explicit in that the ledger is Ethereum, the asset is Erc20.  HAlight and Han fail to do so, as a result we ended up using identifiers that include the protocl, the ledger, and the asset (e.g. HanEtheremEtherHanBitcoinBitcoin), this is the generic abstraction referred to above.

## Goal

We would like to write nice clean code that fully describes itself but is not falsely generic or containing unnecessary layers of abstraction.  We do not, and never will, support _all_ combinations of protocol pairs (e.g. HanBtc <-> HALight(bitcoin)).  Actually we only intend on supporting a small subset of combinations.

We may be better off if we have protocols that fully describe themselves i.e., there is a protocol for each ledger/asset combination that is useful to us.

Finally, if our abstractions lend themselves to writing clean code we all win.

### Ethereum ERC20 Tokens

HErc20 is well named (as stated above).  As an identifier `Herc20` it works as it does as a module name `her20`.  The English acronym capitalisation is however prone to error (Erc20, ERc20, ERC20).

### Htlc Native Asset protocols (currently bitcoin and ether)

This is one of the root causes of the extremely long identifiers currently being used.  If we can fix this into two separate protocol names our code will be easier to read and write.

Background thoughts: We would like to keep the HTLC explicit, the 'native' implies the ledger so is also valuable.  We could use `HanBtc` and `HanEth` but this is basically using 'inheritance', 'han' is an abstract protocol.  It would be nice if we could get away from this abstract-ness.

### Lightning

Currently we have HALight, this does not explicitly state the asset - this may bite use if/when folks start using COMIT on top of Bitcoin clones.

'halight' has the very real benefit of being distinct and easy to read/write, we should steer clear of complicated acronyms that are hard to read/write (like 'hlnbtc') otherwise we will end up with identifiers in our codebase like this `HlnbtcHerc20` - that is not nice at all.

## Reference

A discussion thread can be found on [this PR](https://github.com/comit-network/comit-rs/pull/2513#pullrequestreview-399630409), please see this link for more naming ideas.

**Comment by da-kami** [comment]
Some of my thoughts:

At least in my head one important goal of the naming spike was to define "protocol families" in a way. Something that one can easily refer to in a conversation without having to refer to specific ledgers "that COMIT HAN protocol" and everybody knows what's meant. 

`HAN` was a bundle we could come up with, because it is already (quite) well-defined.

Since we could not find a proper, well-defined abstraction for `HALight` we kept the name specific, with the option to create an abstraction later.

`HErc20` is a specific case. We actually tried to come up with an abstraction for "on top of a ledger" rather than native, but had trouble defining it properly. That's why we went for a specific name again.

If it is necessary to be ledger specific (for code structure, etc.) reasons, I don't see a problem with that.
I would, however, keep the `HAN` "protocol family" in documentation etc. 

---

Ledger-specific `HAN` names that would sound better, but are not as community friendly (because BTC and ETH is already well established):

- HanBi
- HanEt

also works with 3 chars:

- HanBit
- HanEth

🤷‍♂️
