### ISSUE TITLE
anyhow::Result qualified path

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2734]
## Problem

We almost always use `anyhow::Result` throughout cnd. Using the qualified path instead of a use statement is overly verbose. We can import anyhow without any loss of meaning.

## Goal

Remove all the uses of `anyhow::Result` and replace them with an import statement and plain `Result`

**Comment by tcharding** [comment]
This can be described as a stylistic issue - @thomaseizinger and I discussed it but did not reached consensus. I guess we will just have to have a death match of some sort to choose the style.

**Comment by thomaseizinger** [comment]
I've been thinking about this and discovered something groundbreaking that voids all my previous arguments. Sorry if you have explained that in the past and I just wasn't listening properly:

1. `anyhow::Result` is just a type alias, meaning one could write: `anyhow::Result<FooBar, MyError>`. 
2. Usage in the form of `Result<FooBar>` directly tells you that there must be a type-alias otherwise the code wouldn't compile.

I always knew (1) but never thought about the fact that (2) is actually not ambiguous with `std::result::Result` because `std::result::Result` wouldn't compile with a single type parameter.

Now, even though I knew (1), I didn't fully comprehend that it is actually backwards compatible with `std::result::Result` because it is the same type (lol). Meaning, you can just mix and match the usage as you want.
For some reason, I always thought you have to remove the import and qualify all usages of `Result` as soon as you don't want `anyhow::Error`.

Given that, the only other argument for not importing `anyhow::Result` is that it always adds an import line, making that section slightly more verbose (esp. if we keep doing this).

I think all my previous arguments are void through this discovery. Sorry for not actually thinking about this in more depth earlier, I don't see any reason why we shouldn't do `use anyhow::Result` in every file :)
