### ISSUE TITLE
How to secure the `cnd` HTTP API with HTTPS?

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#477]
Answer the following questions:

- comit-i should be able to be served via HTTPS
- API should be accessible via HTTPS
- how to install the certificate?
- does it have to be self-signed? is there any funny workaround for localhost-only HTTPS APIs?

**Comment by D4nte** [comment]
To review once the architecture is such as an application would talk to a remove comit node

**Comment by D4nte** [comment]
this bug is due to lack of password protection.
But then, you wrote:
> You're right, authentication maybe not for now. 
Looks like to me we are specifically looking into password protect here.

Please note that using https for the API bring another array of issue (ie, if using webapp then browser need to accept self-signed certificate).

Also, COMIT does not touch the funds so I see it as a lesser risk.

**Comment by tcharding** [comment]
> Also, COMIT does not touch the funds so I see it as a lesser risk.

A man-in-the-middle attacker could change the address  shown to the user then the user would transfer funds not to the HTLC but to an arbitrary address.  Please correct me if I am wrong.

**Comment by bonomat** [comment]
> > Also, COMIT does not touch the funds so I see it as a lesser risk.
> 
> A man-in-the-middle attacker could change the address shown to the user then the user would transfer funds not to the HTLC but to an arbitrary address. Please correct me if I am wrong.

That's correct.
