### ISSUE TITLE
⚗️ Re-architecting state machine

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#576]
DoD:
* Presentation of the new architecture including upsides and downsides.
* New issues ready to be groomed, under a new Epic.
* Current "Refund" issues updated/deleted.
* How do we get refund with this re-architecture (without new "refundable" states).
* How do we add "secret reveal" before redeem transaction is confirmed (mempool).

**Comment by LLFourn** [comment]
## Forward

While doing this spike I realised this problem can be split into to:

1. What we store in the storage layer is too tightly coupled to our state machine. We shouldn't parameterize our state machine by the `Role` (and even worse have an instance of `role` inside the state machine!).
2. I don't think we shouldn't have a single state machine across both ledgers but rather individual state machines for alpha and beta ledgers.

I decided that fixing (1) first is the most useful because once that's done we can restructure the state machines however we want.

## Problem
Right now we have a very tight coupling between states in the state machine and actions. The HTTP controllers themselves are able to get the current state from the `state_store`. This means that if we want to add new actions or represent new knowledge we have to do so by adding new states. For example:

- To add refund actions we have to create new `Refundable` states for every situation where you could refund one or the other
- To represent the fact that you can learn the secret from a tx in the mempool before it's confirmed you would have to have some new set of states to represent "I've learned the secret but the beta ledger redeem hasn't happened yet"

Doing the above leads to a combinatorial explosion of new states. The purpose of the ticket is to discover a way to decouple *what* we store from *how* we store it. We should store things that make it easy to produce actions and responses for the HTTP api. If the state machine has many complicated states we shouldn't necessarily have to deal with them when producing actions.

## Solution

Instead of storing state machine states we store `Alice` or `Bob` structs which represent the actor's knowledge at the current time. This includes their view of the ledgers, the request/response data and anything else they learn during the execution of the protocol (e.g. learning the secret early from the mempool). From the outside we retrieve `Alice` or `Bob` from the storage layer and ask them for the actions or details about what they know. For example, here's what an `Actor` trait might look like (we may not even need this trait but it's here to help the exposition):

```rust

/// This is what we are able to pull out of the DB. Each variant represents the transactions on the blockchain at the time
enum LedgerState<L: Ledger> {
    None,
    //probably a Deploy in here too but ommitted for clarity
    Funded{
       htlc_location: L::HtlcLocation,
       // we might not even need this if we transition to time based locks rather than block height
       refundable: bool
    },
    Redeem{ htlc_location: L::HtlcLocation, redeem_tx: RedeemTransaction<L> },
    Refund{ htlc_location: L::HtlcLocation, refund_tx: RefundTransaction<L> }
}

trait Actor<AL, BL, AA, BA> {
    /// The enum of actions
    type ActionKind;

    /// The actions the actor can do right now
    fn actions(&self) -> Vec<Self::ActionKind>;

    /// The actor's view of what has happened on the ledgers
    fn alpha_ledger_state(&self) -> LedgerState<AL>;
    fn beta_ledger_state(&self) -> LedgerState<BL>;

    /// Returns something like what `Initiation` contains now
    /// alpha_ledger_refund_identity, alpha_ledger, secret_hash etc
    /// (whatever we specify as the initial data in rfc003 + rfc002)
    fn initial_data -> InitialData<AL,BL,AA,BA>;

    /// What we specify should be in the accept/reject resoinse (if we have it)
    fn response_data -> Option<Result<AcceptResponse<AL,BL>, SwapReject>>;
}
```
## Implementation
Here's how we can realise the above API. We take the `Alice` and `Bob` types that implement `Role` and restructure them so they can implement `Actor`. An implementation of Bob might look like (with some things omitted):

```rust

struct Bob<AL, BL, AA, BA> {
    /// The swap request data
    initial_data: InitialData<AL, BL, AA, BA>,
    alpha_ledger_state: LedgerState<AL>,
    beta_ledger_state: LedgerState<BL>,
    /// When the secret gets revealed before the transaction is confirmed in the mempool
    /// The beta ledger state machine is responsible for changing this value
    early_secret_reveal: Option<Secret>

    /// This is something similar to what `response_sender` is right now but it actually stores
    /// the response once the accept/decline action is taken
    response_state: ResponseState,

    /// we may have ended in failure and aborted execution
    error: Option<rfc003::Erorr>
}

Actor for Bob<Bitcoin, Ethereum, BitcoinQuantity, EtherQuantity> {
    /// Pretty much what we have now
    type ActionKind = alice::ActionKind;

    fn actions(&self) -> Vec<&Self::ActionKind> {
        match (self.alpha_ledger_state, self.beta_ledger_state) {
            (LedgerState::None, LedgerState::None) => {
                // This is very rough
                self.response_state.get_response() {
                    NoResponseYet(accept_action, decline_action) => vec![accept_action, decline_action],
                    _ => vec![],
                }
            },
            (LedgerState::Funded{...}, LedgerState::None) => {
                vec![bob::ActionKind::Fund(swap.fund_action())]
            },
            (LedgerState::Funded{...}, LedgerState::Funded{refundable, beta_htlc_location}) => {
                if refundable {
                    let data = Bytes::default();
                    let gas_limit = EtherHtlc::tx_gas_limit();
                    vec![bob::ActionKind::Refund(ethereum::SendTransaction {
                        to: beta_htlc_location,
                        data,
                        gas_limit,
                        value: EtherQuantity::zero(),
                    }]
                }
                else {
                    vec![]
                }
            }
            // etc
        }
    }

    // The other methods just return the data bob has access to
}
```

### Storing data

Right now we use the `transition_save` macro to change states. Instead of storing the state in this case we should store the necessary data on each transition.

**Comment by D4nte** [comment]
You are avoiding the creation of a new `Refundable` state by adding a `bool` to the `Funded` state. Instead of explicitly splitting into two state `FundedNonRefundable` and `FundedRefundable` you do it implicitly by adding a `bool` to the `Funded` state (ie, creating *sub-states*).

Also, the `Refundable` part may not be a state of the blockchain per say.
The state of the blockchain is "block X has been mined", if `X = expiry` then yes, it becomes refundable and you could consider it a state.

Now, let's say we want to restrict the `BothFunded` state to be only within a given timeframe for Alice. E.g., we do not want Alice to redeem the beta ledger if we are within 1 hour of the expiry of the beta HTLC.
One way would be to add a `safely_redeemable` boolean to the `BothFunded` state (for Alice).
But it does not seem correct as it does not describe a blockchain state but better an interpretation of the blockchain state.

Would it make more sense to add a property to this state such as `blockchain_height` and then use this property to generate the actions? This `blockchain_height` can then be used to generate (or not) the `redeem` and `refund` actions.

Let me know your thoughts.

**Comment by LLFourn** [comment]
The tickets I would create to realise this:

1. Remove all the associated types from `Role` and store the keys and the secret inside Alice and Bob. For now we would leave the role in the state and the `Actions` trait implemented on `SwapStates`.

Then in actions we would ask Bob and Alice for the redeem and refund actions (like we ask Bob for the accpet and decline actions currently).

2. Make all of the above changes

**Refund feature**: To get the refund feature we might not even need these changes because I think we can just use the system time. We have to transition away from Block height to timestamp because of the security issues with variable block times. To do it properly we would need these changes and then write to the storage layer at the earliest time we could possibly refund.

**Early secret reveal**: To do this I think we would need these changes. Once again we'd just set up a query which resolves as soon as the secret hits the mempool. When it does we'd write to storage that this has happened.

**Comment by LLFourn** [comment]
> You are avoiding the creation of a new `Refundable` state by adding a `bool` to the `Funded` state. Instead of explicitly splitting into two state `FundedNonRefundable` and `FundedRefundable` you do it implicitly by adding a `bool` to the `Funded` state (ie, creating _sub-states_).

Yes. Keep in mind The `LedgerState` **is not a state machine state**. It's simply what's stored in the storage layer/database.

> Also, the `Refundable` part may not be a state of the blockchain per say.
> The state of the blockchain is "block X has been mined", if `X = expiry` then yes, it becomes refundable and you could consider it a state.
You would still need a to know when this has happened. The point about this change is that whenever this does happen you can just write it to the storage layer. You don't have to do it in the state machine.

> Now, let's say we want to restrict the `BothFunded` state to be only within a given timeframe for Alice. E.g., we do not want Alice to redeem the beta ledger if we are within 1 hour of the expiry of the beta HTLC.
> One way would be to add a `safely_redeemable` boolean to the `BothFunded` state (for Alice).
> But it does not seem correct as it does not describe a blockchain state but better an interpretation of the blockchain state.
Yes. This is exactly the point of this change. So we can write flags like `safely_redeemable` to the storage layer without having to represent them as states in the state machine.

> Would it make more sense to add a property to this state such as `blockchain_height` and then use this property to generate the actions? This `blockchain_height` can then be used to generate (or not) the `redeem` and `refund` actions.
You should see my comments about not using block height anymore.
Add them to where?
> Let me know your thoughts.

**Comment by LLFourn** [comment]
I think I'll leave this open until @thomaseizinger has had a look.

**Comment by LLFourn** [comment]
After discussing with team it looks like this is the best way forward but we can put these changes on hold until we have a concrete issue with the current model.
