### ISSUE TITLE
⚗️ How to realize same chain trades on Ethereum

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#665]
DoD
- [x] Present a lightly documented protocol
- [x] Create issue to write the RFC

Child of #663

**Comment by bonomat** [comment]
Note: there is one error in your description but I assume you meant the following:

 * Alice deploys the HTLC contract including ETH
  * Bob calls `transfer(htlc_contract, amount)` on the token contract to transfer the `amount` of tokens to the HTLC contract.
  * Alice redeems the Ether from the HTLC contract (`transfer(alice_address, amount)` is called) by sending the secret to it 

(same same but different for the otherway around :D )

Two thoughts on that:

1) Alternatively, in order to not loose tokens by mistake, Bob could call `approve(thlc_contract, amount)` on the token contract so that the HTLC contract can call `transfer_from(bob_address, alice_address, amount)`. 

2) I don't think we can get rid of having at least 3 transactions (same applies in two directions). Bob (or Alice) will always need at least 2 transactions to transfer (or allow a transfer) the tokens to the HTLC contract the redemption of the HTLC + 1 transaction for the deployment/funding

Afaik, even if we have a stateful contract, we will need these 3 transactions, however, we can get rid of the costly HTLC deployment transaction.

**Comment by LLFourn** [comment]
@bonomat The goal of the protocol is for it to be non-interactive. So Alice puts up the contract and **lets anyone in the world** take the trade without interacting with her (Bob is just the name of the guy who was fastest to take the offer). I'll add more details making this clearer.

It does seem like we'll always need three transactions, which is lame because Bitcoin only takes one to do the same thing.

**Comment by D4nte** [comment]
Yes I was going to say, how come the contract can transfer Bob's ERC20? I guess Bob needs to give it the right to transfer them, right?

**Comment by LLFourn** [comment]
@bonomat @D4nte I rewrote the original to include missing pieces and motivation.
>True, an actual HTLC is not needed. Just replace HTLC in my description with contract.
To condition a same chain trade on a cross chain trade? Yes in this case you would need a HTLC. You could use a single HTLC that holds two assets to do this. This would definitely be a different RFC/contract.

**Comment by thomaseizinger** [comment]
I like the idea of non-interactive trades. Good stuff.

We should investigate whether `msg.sender` is `Bob` or the `contract` if Bob directly invokes the contract. If not, `Bob` will have to approve the token transfer first.

# Gas considerations

In order to make things really atomic, we will have to look into:

1. How to revert state changes while calling other contracts
2. Make sure we have enough gas at the beginning to do all the stuff we need

# RFC considerations

I think there should be 1 RFC that specifies same chain trades on Ethereum between Ether and ERC20.
Seems like a reasonable scope.

# BAM considerations

Since it is non-interactive, this will neither use the `SWAP` message, nor need a new message type. Cool!

# HTTP API considerations

Very likely a new sub-resource under `/swaps` with the given RFC number. Since we don't need communication and it is a new resource, we can leave out the peer address here.

**Comment by bonomat** [comment]
Before we jump into non-interactive trades on Ethereum and write a RFC, please have a look at all the decentralized exchanges out there. To name a few: 0x, etherdelta , kyber network , idex, waves, ethfinex , radar... 

Most of them are completely open source and provide a proper protocol to use.

We might need to clarify the goal of this ticket but if it's just Ethereum same chain trades, than we can really just use a solution which is out there already and skip the RFC.

I think the fun part is when the protocol enables multi-hop trades on the same chain or in combination with cross-chain, partially execution of trades.

**Comment by LLFourn** [comment]
> I like the idea of non-interactive trades. Good stuff.
Yes. Same chain trades are far better because the blockchain itself is the decentralised exchange. The COMIT node can still play a role in verifying and interpreting the blockchain I think.
> We should investigate whether `msg.sender` is `Bob` or the `contract` if Bob directly invokes the contract. If not, `Bob` will have to approve the token transfer first.
I looked into this and unfortunately it looks like Bob has to do an approve first.
> # Gas considerations
> In order to make things really atomic, we will have to look into:
> 
> 1. How to revert state changes while calling other contracts
There's a `REVERT` instruction in EVM which seems to do the trick.
> 2. Make sure we have enough gas at the beginning to do all the stuff we need
If we run out of gas it should `REVERT` everything.

> # HTTP API considerations
> Very likely a new sub-resource under `/swaps` with the given RFC number. Since we don't need communication and it is a new resource, we can leave out the peer address here.
Yes I guess you just have a system that whenever if finds a possible same chain trade on ethereum it posts it to the COMIT node which verifies it and produces the actions to "approve" and then poke the contract.

**Comment by thomaseizinger** [comment]
> Yes I guess you just have a system that whenever if finds a possible same chain trade on ethereum it posts it to the COMIT node which verifies it and produces the actions to "approve" and then poke the contract actions.

Very interesting point. I didn't even think that far :)

**Comment by thomaseizinger** [comment]
@bonomat 

> Before we jump into non-interactive trades on Ethereum and write a RFC, please have a look at all the decentralized exchanges out there. To name a few: 0x, etherdelta , kyber network , idex, waves, ethfinex , radar...

Are you saying we should copy the protocol or make the COMIT node compatible with any of those exchanges?

**Comment by bonomat** [comment]
@thomaseizinger 
> Are you saying we should copy the protocol or make the COMIT node compatible with any of those exchanges?

Using one obviously :) 

@LLFourn 
> > I like the idea of non-interactive trades. Good stuff.
> 
> Yes. Same chain trades are far better because the blockchain itself is the decentralised exchange. The COMIT node can still play a role in verifying and interpreting the blockchain I think.

In this case we don't need the COMIT node at all:
* a static website with web3 can monitor the blockchain and looks for offers
* signing transactions is done with your ledger/metamask
The result is Etherdelta :D 
 
> > We should investigate whether `msg.sender` is `Bob` or the `contract` if Bob directly invokes the contract. If not, `Bob` will have to approve the token transfer first.
> 
> I looked into this and unfortunately it looks like Bob has to do an approve first.

Correct, we verified that in our last hackathon remember?
If `Bob` issues a transaction he is `msg.sender`. If a contract forwards the transaction (i.e. `call` is invoked) then `msg.sender` is the contract. The thing we were confused about last time was that during a contract deployment `msg.sender` is already the contract and not Bob who was the sender of that transaction. 

> > # Gas considerations
> > In order to make things really atomic, we will have to look into:
> > 
> > 1. How to revert state changes while calling other contracts
> 
> There's a `REVERT` instruction in EVM which seems to do the trick.
> 
> > 1. Make sure we have enough gas at the beginning to do all the stuff we need
> 
> If we run out of gas it should `REVERT` everything.

Yes, this is correct. Unless a contract checks for gas and does not call `REVERT` but silently returns false (or ignores an action). I have the feeling we should not do any `gas` checks/assumptions in the contract given the latest problems with Ethereum (https://medium.com/chainsecurity/constantinople-enables-new-reentrancy-attack-ace4088297d9).

**Comment by LLFourn** [comment]
Talked with @bonomat  and came to the following outcome for this ticket:

1. Before implementing our own non-interactive same chain trades on Ethereum we should check out existing contracts and protocols that do this already.
2. If we need to design interactive same chain ethereum trades that can be conditioned on the outcome of the HTLC we should do the research into that when we come to that requirement.

**Comment by D4nte** [comment]
DoD:
- [ ] Team discussion needed to decide on how we want to proceed with same chain swaps

**Comment by D4nte** [comment]
Let's wait until everyone is in office.

**Comment by D4nte** [comment]
Meeting invite sent for Monday.

**Comment by D4nte** [comment]
Unblock, @LLFourn to write down decisions.

**Comment by LLFourn** [comment]
We left the discussion with the following resolutions:
1. Ethereum same chain swaps can be non-interactive (like the protocol I describe above and things like EtherDelta etc). Since these protocols don't require any inter-party communication they are not within the scope of COMIT.
2. If we were to create an interactive same chain swap protocol (so you can do a swap with a particular person) that would be part of COMIT but we should wait until we have a proper motivation for this.
