### ISSUE TITLE
Include cause for deserialization error in HTTP response

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#754]
The cause of the deserialization error should be extracted from the `serde_json::Error`:

https://github.com/comit-network/comit-rs/blob/9f9a8d3efc7f89f2451ea12039c0d7def97ab886/application/comit_node/src/http_api/problem.rs#L46

Currently, we only return a 400 to the user which does not help to resolve the problem. We should aim to return more details in the http response. Examples of what would be helpful:

- "Unexpected field `foobar`"
- "Invalid type for field `alpha_expiry`, expected u32, got string"

Degree of detail will greatly depend on what serde exposes over the API of the error.

**Comment by thomaseizinger** [comment]
The situation improved a fair bit with https://github.com/comit-network/comit-rs/pull/1723.

As the comment in the PR says, it is hard to provide better errors without deserializing everything manually because serde only returns messages and not structural information of what went wrong.

Will close this for now. If the current errors are not sufficient, we can always open up a new issue.
