### ISSUE TITLE
⚗️Investigate ways for outsourcing network layer

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#779]
We currently implement on our network layer (connection handling and pooling, encryption).

Look at libraries that could alleviate the load in this area.
Consider the following properties:
- encryption
- identification
- NAT

This is a follow-up of #739 
Required by #655
Required by #651
Required by #746
Required by #735
Required by #736

**Comment by thomaseizinger** [comment]
I wasn't sure how to best approach the research so I simply looked through all crates on crates.io that were tagged with `network` or `networking`:

- https://crates.io/keywords/networking
- https://crates.io/keywords/network

One thing that came up apart from libp2p which looks interesting is this:

https://github.com/tox-rs/tox

It describes itself as:

> a P2P, distributed, encrypted, easy to use DHT-based network.

Other than that, most results where either small libraries or low-level network stacks like:

- https://github.com/libpnet/libpnet
- https://github.com/QuiltOS/QuiltNet

Why did choose to just go through crates.io and not google/other search engines:

1. Any software that we could potentially use should be released already. Everything else would be too much of a commitment for something as fundamental as our networking layer.
2. It has to be written in Rust, otherwise there is not really a point.
3. A google search mostly gives you results about "how can I open a socket in Rust and the like :roll_eyes:"

**Comment by D4nte** [comment]
Thanks @thomaseizinger I am satisfied. Go libp2p.

**Comment by bonomat** [comment]
I think `libp2p` is the way to go, it is well maintained, has other usecases which depend on it (ipfs) and it feels it's well-respected in the blockchain community.

**Comment by thomaseizinger** [comment]
Thanks for your feedback. I'll consider this to be done then!
