### ISSUE TITLE
PoC implementation of Scriptless Scripts with ECDSA

### ISSUE THREAD

**Issue by LLFourn** [comit-network/comit-rs#963]
Using the primitives from:

- https://github.com/KZen-networks/multi-party-ecdsa
- https://github.com/KZen-networks/multi-hop-locks

and the results from:
- https://github.com/comit-network/comit-rs/issues/897
- https://github.com/comit-network/comit-rs/issues/899

implement a PoC scriptless scripts exchange where:
1. Parties agree on a joint public key
2. One party wants to have a ECDSA signature to under the public key on  a message
3. The other party wants to learn a discrete logarithm that (2) knows

Verify the signatures using the libsecp256k1 ECDSA verify function.
Don't worry about signing actual transactions but just sign a message like "Alice gives bob 1 bitcoin". 
This is off-chain and just one file to demonstrate the "learning" (point 3).

**Comment by LLFourn** [comment]
Review new repo at: https://github.com/coblox/ss-ecdsa-poc

**Comment by LLFourn** [comment]
I'm happy with this as a PoC for this stage now.
It needs further security review before being used in production.

**Comment by thomaseizinger** [comment]
I only looked at the code from a SE perspective and how it would fit into the comit-rs.

I think the PoC provides a useful low-level library for scriptless scripts. In order to actual use it, another layer has to be built on top of it that provides a uniform interface (one `Message` type and only a single state `struct`). That should easily be possible though. Most importantly, the library provides a type-safe interface that strictly mandates the order of execution and the messages that need to be passed back and forth.

Very well done @LLFourn !

**Comment by bonomat** [comment]
Obsolete as we will make another different attempt towards SS.
