### ISSUE TITLE
Align network layer with recent revision of RFC-001

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#995]
A [recent revision of the RFC](https://github.com/comit-network/RFCs/pull/60) removed the concept of `StatusCode` and introduced `ERROR` frames instead (for some use-cases).

- [ ] align the implementation with the description in the RFC

**Comment by tcharding** [comment]
While working on this issue @da-kami, @thomaseizinger and myself have discovered the following:
- Perhaps adding an ERROR frame is not a good idea.  We definitely want to be able to indicate errors at the messaging layer but there may be more succinct methods of doing so.
- Writing/updating the RFC before writing code may not be the best process since it is easy to [over] specify something that turns out to be not that easily implemented.  Also the implementation may lead to a cleaner solution.  It is not clear that just implementing first without thinking about the specification is a better method either :)

**Comment by da-kami** [comment]
As @tcharding already pointed out the introduction of the `Error` frame in code sparked several problems. The conclusion: The status code was removed, there atm there is no feedback for the counterparty upon messaging errors. 

See https://github.com/comit-network/RFCs/issues/117 and https://github.com/comit-network/RFCs/issues/116
